{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 8, "minor": 6, "revision": 5, "architecture": "x64", "modernui": 1},
    "classnamespace": "box",
    "rect": [70.0, 70.0, 1280.0, 780.0],
    "boxes": [
      {"box":{"id":"title","maxclass":"comment","text":"GENDY3 / PARAG visual study — 4 stochastic trajectories → 4 Cycle voices","fontsize":22.0,"patching_rect":[35.0,24.0,850.0,32.0]}},
      {"box":{"id":"intro","maxclass":"comment","text":"Bang «generate section»: exponential time fields + Bernoulli silences; Cauchy impulse → bounded primary walk → bounded amplitude walk.","patching_rect":[37.0,60.0,970.0,20.0]}},
      {"box":{"id":"generate","maxclass":"button","patching_rect":[40.0,110.0,30.0,30.0]}},
      {"box":{"id":"generate_label","maxclass":"comment","text":"generate section","patching_rect":[80.0,115.0,130.0,20.0]}},
      {"box":{"id":"reset","maxclass":"message","text":"reset","patching_rect":[230.0,114.0,42.0,22.0]}},
      {"box":{"id":"js","maxclass":"newobj","text":"js gendy3_mcfunction.js","patching_rect":[40.0,170.0,152.0,22.0]}},
      {"box":{"id":"lineout","maxclass":"message","text":"lineout $1","patching_rect":[40.0,215.0,68.0,22.0]}},
      {"box":{"id":"function","maxclass":"newobj","text":"mc.function @chans 4 @displaychan 0 @classic_curve 1","patching_rect":[250.0,125.0,630.0,250.0],"parameter_enable":0}},
      {"box":{"id":"function_note","maxclass":"comment","text":"Each coloured line is one independent voice. X = time-field succession; Y = secondary amplitude-walk position (centre line = Bernoulli silence).","linecount":2,"patching_rect":[900.0,150.0,300.0,40.0]}},
      {"box":{"id":"line","maxclass":"newobj","text":"mc.line~ @chans 4","patching_rect":[250.0,420.0,118.0,22.0]}},
      {"box":{"id":"scale","maxclass":"newobj","text":"mc.*~ 720.","patching_rect":[250.0,465.0,84.0,22.0]}},
      {"box":{"id":"offset","maxclass":"newobj","text":"mc.+~ 120.","patching_rect":[250.0,505.0,84.0,22.0]}},
      {"box":{"id":"cycle","maxclass":"newobj","text":"mc.cycle~ @chans 4","patching_rect":[250.0,545.0,120.0,22.0]}},
      {"box":{"id":"voicegain","maxclass":"newobj","text":"mc.*~ 0.16","patching_rect":[250.0,585.0,88.0,22.0]}},
      {"box":{"id":"mix","maxclass":"newobj","text":"mc.mixdown~ 1","patching_rect":[250.0,625.0,102.0,22.0]}},
      {"box":{"id":"gendy","maxclass":"newobj","text":"poly~ gendy3_voice 8 @parallel 1","patching_rect":[430.0,545.0,190.0,22.0]}},
      {"box":{"id":"gendyamp","maxclass":"newobj","text":"*~ 0.12","patching_rect":[430.0,580.0,62.0,22.0]}},
      {"box":{"id":"tapin","maxclass":"newobj","text":"tapin~ 150.","patching_rect":[510.0,580.0,74.0,22.0]}},
      {"box":{"id":"tapout","maxclass":"newobj","text":"tapout~ 100.","patching_rect":[600.0,580.0,86.0,22.0]}},
      {"box":{"id":"gain","maxclass":"live.gain~","patching_rect":[430.0,610.0,150.0,48.0],"parameter_enable":0}},
      {"box":{"id":"dac","maxclass":"ezdac~","patching_rect":[640.0,610.0,45.0,45.0]}},
      {"box":{"id":"audio_note","maxclass":"comment","text":"Audio renderer: 8 direct GENDY breakpoint voices; the right channel is a 100 ms delayed second pass, following GENDY3’s documented pseudo-stereo procedure. mc.function shows the PARAG architecture.","linecount":3,"patching_rect":[730.0,600.0,430.0,58.0]}},
      {"box":{"id":"load","maxclass":"newobj","text":"loadbang","patching_rect":[40.0,270.0,58.0,22.0]}},
      {"box":{"id":"number1","maxclass":"flonum","minimum":0.0,"maximum":1.0,"patching_rect":[40.0,320.0,54.0,22.0]}},
      {"box":{"id":"probmsg","maxclass":"newobj","text":"prepend setprobability","patching_rect":[105.0,320.0,142.0,22.0]}},
      {"box":{"id":"probnote","maxclass":"comment","text":"sounding probability","patching_rect":[255.0,321.0,130.0,20.0]}},
      {"box":{"id":"number2","maxclass":"flonum","minimum":1.0,"maximum":200.0,"patching_rect":[40.0,355.0,54.0,22.0]}},
      {"box":{"id":"fieldmsg","maxclass":"newobj","text":"prepend setfieldmean","patching_rect":[105.0,355.0,136.0,22.0]}},
      {"box":{"id":"fieldnote","maxclass":"comment","text":"mean exponential time field","patching_rect":[255.0,356.0,200.0,20.0]}},
      {"box":{"id":"p72","maxclass":"message","text":"0.72","patching_rect":[470.0,321.0,40.0,22.0]}},
      {"box":{"id":"p78","maxclass":"message","text":"78.","patching_rect":[470.0,356.0,40.0,22.0]}}
    ],
    "lines": [
      {"patchline":{"source":["generate",0],"destination":["js",0]}},
      {"patchline":{"source":["reset",0],"destination":["js",0]}},
      {"patchline":{"source":["js",0],"destination":["lineout",0]}},
      {"patchline":{"source":["lineout",0],"destination":["function",0]}},
      {"patchline":{"source":["js",1],"destination":["function",0]}},
      {"patchline":{"source":["function",0],"destination":["line",0]}},
      {"patchline":{"source":["line",0],"destination":["scale",0]}},
      {"patchline":{"source":["scale",0],"destination":["offset",0]}},
      {"patchline":{"source":["offset",0],"destination":["cycle",0]}},
      {"patchline":{"source":["cycle",0],"destination":["voicegain",0]}},
      {"patchline":{"source":["voicegain",0],"destination":["mix",0]}},
      {"patchline":{"source":["gendy",0],"destination":["gendyamp",0]}},
      {"patchline":{"source":["gendyamp",0],"destination":["gain",0]}},
      {"patchline":{"source":["gendyamp",0],"destination":["tapin",0]}},
      {"patchline":{"source":["tapout",0],"destination":["gain",1]}},
      {"patchline":{"source":["gain",0],"destination":["dac",0]}},
      {"patchline":{"source":["gain",1],"destination":["dac",1]}},
      {"patchline":{"source":["load",0],"destination":["p72",0]}},
      {"patchline":{"source":["load",0],"destination":["p78",0]}},
      {"patchline":{"source":["load",0],"destination":["generate",0]}},
      {"patchline":{"source":["p72",0],"destination":["number1",0]}},
      {"patchline":{"source":["p78",0],"destination":["number2",0]}},
      {"patchline":{"source":["number1",0],"destination":["probmsg",0]}},
      {"patchline":{"source":["probmsg",0],"destination":["js",0]}},
      {"patchline":{"source":["number2",0],"destination":["fieldmsg",0]}},
      {"patchline":{"source":["fieldmsg",0],"destination":["js",0]}}
    ]
  }
}
