{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 8, "minor": 6, "revision": 5, "architecture": "x64", "modernui": 1},
    "classnamespace": "box",
    "rect": [120.0, 120.0, 800.0, 500.0],
    "boxes": [
      {"box": {"id": "obj-1", "maxclass": "newobj", "text": "gen~", "patching_rect": [160.0, 160.0, 42.0, 22.0], "patcher": {"fileversion": 1, "appversion": {"major": 8, "minor": 6, "revision": 5, "architecture": "x64"}, "classnamespace": "dsp.gen", "rect": [0.0, 0.0, 800.0, 500.0], "boxes": [
        {"box": {"id": "g1", "maxclass": "codebox", "numinlets": 1, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [80.0, 60.0, 610.0, 330.0], "code": "Param dMin(18);\nParam dMax(48);\nParam dVelocity(1.5);\nParam dImpulse(0.08);\nParam ampLimit(0.45);\nParam aVelocity(0.025);\nParam aImpulse(0.002);\nHistory ph(0);\nHistory d1(25); History d2(30); History d3(36); History d4(42);\nHistory dv1(0); History dv2(0); History dv3(0); History dv4(0);\nHistory a1(0.1); History a2(-0.2); History a3(0.25); History a4(-0.1);\nHistory av1(0); History av2(0); History av3(0); History av4(0);\nperiod = max(4, d1 + d2 + d3 + d4);\nnextPh = ph + (1 / period);\nwrapped = nextPh >= 1;\nph = nextPh - floor(nextPh);\n// Two-level reflected walks: random acceleration -> primary velocity -> breakpoint.\nndv1 = fold(dv1 + noise() * dImpulse, -dVelocity, dVelocity);\nndv2 = fold(dv2 + noise() * dImpulse, -dVelocity, dVelocity);\nndv3 = fold(dv3 + noise() * dImpulse, -dVelocity, dVelocity);\nndv4 = fold(dv4 + noise() * dImpulse, -dVelocity, dVelocity);\nnav1 = fold(av1 + noise() * aImpulse, -aVelocity, aVelocity);\nnav2 = fold(av2 + noise() * aImpulse, -aVelocity, aVelocity);\nnav3 = fold(av3 + noise() * aImpulse, -aVelocity, aVelocity);\nnav4 = fold(av4 + noise() * aImpulse, -aVelocity, aVelocity);\nnewd1 = fold(d1 + ndv1, dMin, dMax); newd2 = fold(d2 + ndv2, dMin, dMax);\nnewd3 = fold(d3 + ndv3, dMin, dMax); newd4 = fold(d4 + ndv4, dMin, dMax);\nnewa1 = fold(a1 + nav1, -ampLimit, ampLimit); newa2 = fold(a2 + nav2, -ampLimit, ampLimit);\nnewa3 = fold(a3 + nav3, -ampLimit, ampLimit); newa4 = fold(a4 + nav4, -ampLimit, ampLimit);\ndv1 = mix(dv1, ndv1, wrapped); dv2 = mix(dv2, ndv2, wrapped); dv3 = mix(dv3, ndv3, wrapped); dv4 = mix(dv4, ndv4, wrapped);\nav1 = mix(av1, nav1, wrapped); av2 = mix(av2, nav2, wrapped); av3 = mix(av3, nav3, wrapped); av4 = mix(av4, nav4, wrapped);\nd1 = mix(d1, newd1, wrapped); d2 = mix(d2, newd2, wrapped); d3 = mix(d3, newd3, wrapped); d4 = mix(d4, newd4, wrapped);\na1 = mix(a1, newa1, wrapped); a2 = mix(a2, newa2, wrapped); a3 = mix(a3, newa3, wrapped); a4 = mix(a4, newa4, wrapped);\np1 = d1 / period; p2 = p1 + d2 / period; p3 = p2 + d3 / period;\ny1 = a1 + (ph / max(p1, 0.00001)) * (a2 - a1);\ny2 = a2 + ((ph - p1) / max(p2 - p1, 0.00001)) * (a3 - a2);\ny3 = a3 + ((ph - p2) / max(p3 - p2, 0.00001)) * (a4 - a3);\ny4 = a4 + ((ph - p3) / max(1 - p3, 0.00001)) * (a1 - a4);\nout1 = (ph < p1) ? y1 : ((ph < p2) ? y2 : ((ph < p3) ? y3 : y4));"}}
      ], "lines": []}}},
      {"box": {"id": "obj-2", "maxclass": "outlet", "outlettype": ["signal"], "patching_rect": [160.0, 250.0, 25.0, 25.0]}},
      {"box": {"id": "obj-3", "maxclass": "comment", "text": "One GENDY voice: four breakpoint durations and amplitudes move through bounded second-order random walks.", "patching_rect": [160.0, 90.0, 580.0, 20.0]}}
    ],
    "lines": [{"patchline": {"source": ["obj-1", 0], "destination": ["obj-2", 0]}}]
  }
}
